name: Build Vial Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install QMK dependencies
        run: |
          pip install qmk

      - name: Build firmware
        run: |
          qmk setup -H . --yes
          qmk compile -kb ploopyco/madromys/rev1_001 -km vial

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: '*.uf2'
